# Generated by Django 2.1.4 on 2019-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.UUIDField()),
                ('task', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
