# Generated by Django 2.1.4 on 2019-01-29 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_remove_todolist_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='taskid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
