# Generated by Django 2.1.4 on 2019-01-29 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_todolist_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='id',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='taskid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
