# Generated by Django 2.1.4 on 2019-01-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
