# Generated by Django 2.1.4 on 2019-02-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0006_delete_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Normal'), ('3', 'Low')], default=('2', 'Normal'), max_length=10),
        ),
    ]
